<?php
/**
 * @author Florent HAZARD <f.hazard@sowapps.com>
 */

declare(strict_types=1);

namespace App\Entity;

use App\Enum\WorkflowStepTransitionMode;
use App\Enum\WorkflowStepStatus;
use App\Repository\WorkflowStepRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Uid\Uuid;

/**
 * Represents a single step within a workflow, defining input configuration, actions, and execution status.
 */
#[ORM\Entity(repositoryClass: WorkflowStepRepository::class)]
#[ORM\Table(name: 'workflow_step')]
class WorkflowStep
{
    #[ORM\Id]
    #[ORM\Column(type: 'uuid')]
    private Uuid $id;

    #[ORM\ManyToOne(targetEntity: Workflow::class, inversedBy: 'steps')]
    #[ORM\JoinColumn(nullable: false, onDelete: 'CASCADE')]
    private Workflow $workflow;

    #[ORM\Column]
    private int $stepOrder;

    #[ORM\Column(length: 255)]
    private string $name;

    /**
     * Input configuration including source (vcs, previous_step, manual) and parameters.
     */
    #[ORM\Column(type: 'json')]
    private array $inputConfig = [];

    /**
     * Output key produced by this step and consumable by subsequent steps.
     */
    #[ORM\Column(length: 255)]
    private string $outputKey;

    #[ORM\Column(enumType: WorkflowStepTransitionMode::class)]
    private WorkflowStepTransitionMode $transitionMode = WorkflowStepTransitionMode::Manual;

    /**
     * Execution condition such as "previous.issues_count > 0"; null means always execute.
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $condition = null;

    /**
     * Status of the latest execution.
     */
    #[ORM\Column(enumType: WorkflowStepStatus::class)]
    private WorkflowStepStatus $status;

    /**
     * Output generated by the latest execution as raw text or JSON.
     */
    #[ORM\Column(type: 'text', nullable: true)]
    private ?string $lastOutput = null;

    /** @var Collection<int, WorkflowStepAction> */
    #[ORM\OneToMany(targetEntity: WorkflowStepAction::class, mappedBy: 'workflowStep', cascade: ['persist', 'remove'], orphanRemoval: true)]
    private Collection $actions;

    /**
     * Creates a workflow step with its order, display name, and output key.
     */
    public function __construct(
        Workflow $workflow,
        int      $stepOrder,
        string   $name,
        string   $outputKey,
    ) {
        $this->id        = Uuid::v7();
        $this->workflow  = $workflow;
        $this->stepOrder = $stepOrder;
        $this->name      = $name;
        $this->outputKey = $outputKey;
        $this->status    = WorkflowStepStatus::Pending;
        $this->actions   = new ArrayCollection();
    }

    /** Returns the workflow step identifier. */
    public function getId(): Uuid                      { return $this->id; }
    /** Returns the workflow owning the step. */
    public function getWorkflow(): Workflow            { return $this->workflow; }
    /** Returns the ordering index of the step. */
    public function getStepOrder(): int                { return $this->stepOrder; }
    /** Returns the display name of the step. */
    public function getName(): string                  { return $this->name; }
    /** Returns the output key alias of the step. */
    public function getKey(): string                   { return $this->outputKey; }
    /** Returns the input configuration payload. */
    public function getInputConfig(): array            { return $this->inputConfig; }
    /** Returns the output key of the step. */
    public function getOutputKey(): string             { return $this->outputKey; }
    /** Returns the transition mode used by the step. */
    public function getTransitionMode(): WorkflowStepTransitionMode { return $this->transitionMode; }
    /** Returns the execution condition, if any. */
    public function getCondition(): ?string             { return $this->condition; }
    /** Returns the latest execution status. */
    public function getStatus(): WorkflowStepStatus    { return $this->status; }
    /** Returns the latest execution output, if any. */
    public function getLastOutput(): ?string            { return $this->lastOutput; }
    /** @return Collection<int, WorkflowStepAction> */
    public function getActions(): Collection           { return $this->actions; }

    /** Reassigns the owning workflow. */
    public function setWorkflow(Workflow $w): static              { $this->workflow = $w; return $this; }
    /** Updates the step order. */
    public function setStepOrder(int $order): static              { $this->stepOrder = $order; return $this; }
    /** Updates the step display name. */
    public function setName(string $name): static                 { $this->name = $name; return $this; }
    /** Replaces the input configuration payload. */
    public function setInputConfig(array $config): static         { $this->inputConfig = $config; return $this; }
    /** Updates the output key. */
    public function setOutputKey(string $key): static             { $this->outputKey = $key; return $this; }
    /** Updates the transition mode. */
    public function setTransitionMode(WorkflowStepTransitionMode $transitionMode): static { $this->transitionMode = $transitionMode; return $this; }
    /** Updates the execution condition. */
    public function setCondition(?string $cond): static                    { $this->condition = $cond; return $this; }
    /** Updates the latest execution status. */
    public function setStatus(WorkflowStepStatus $s): static               { $this->status = $s; return $this; }
    /** Stores the latest execution output. */
    public function setLastOutput(?string $output): static                 { $this->lastOutput = $output; return $this; }

    /**
     * Adds an action link to the step if it is not already present.
     */
    public function addAction(WorkflowStepAction $action): static
    {
        if (!$this->actions->contains($action)) {
            $this->actions->add($action);
            $action->setWorkflowStep($this);
        }

        return $this;
    }

    /**
     * Removes an action link from the step.
     */
    public function removeAction(WorkflowStepAction $action): static
    {
        $this->actions->removeElement($action);

        return $this;
    }

    /**
     * Marks the step as currently running.
     */
    public function markRunning(): static   { return $this->setStatus(WorkflowStepStatus::Running); }

    /**
     * Marks the step as completed and stores its output.
     */
    public function markDone(string $output): static
    {
        $this->status     = WorkflowStepStatus::Done;
        $this->lastOutput = $output;
        return $this;
    }

    /**
     * Marks the step as failed and stores the error output.
     */
    public function markError(string $error): static
    {
        $this->status     = WorkflowStepStatus::Error;
        $this->lastOutput = $error;
        return $this;
    }

    /**
     * Marks the step as skipped.
     */
    public function markSkipped(): static  { return $this->setStatus(WorkflowStepStatus::Skipped); }
}
